### ISSUE TITLE
Adjustable background filter blur?

### ISSUE THREAD

**Issue by MiMiMeowMeow** [timo-reymann/yal#6]
### Description

Adjustable background filter blur?
Would like to adjust slightly sharper.

**Comment by timo-reymann** [comment]
Supported with 1.5.0 :) 

```env
YAL_BACKGROUND="blur(<your blur>) brightness(0.9)"
```

Where brightness can also be omitted and you can basically use any CSS filter available :)

**Comment by MiMiMeowMeow** [comment]
@timo-reymann Hmmm.. it doesn't seem to make a difference. It looks like zoom in and out acutally changes the background blur...

**Comment by timo-reymann** [comment]
> @timo-reymann Hmmm.. it doesn't seem to make a difference. It looks like zoom in and out acutally changes the background blur...

I suspect that your image is simply not in a corresponding size. When it is is smaller than your screen size it is always tried to make it fit, which means upscaling, which in case of the browser, makes images look a bit blurier.

Can you try with a high-res image or simply upscale your image with e.g. with https://www.upscale.media/
